### ISSUE TITLE
Disable TYPE MISMATCH popups

### ISSUE THREAD

**Issue by anacrolix** [elm-community/Elm.tmLanguage#16]
When I build with cmd+B, if I get type mismatches, they popup in the code window as TYPE MISMATCH, with a little X to close. How can I prevent these from popping up?

<img width="170" alt="screen shot 2017-04-25 at 11 33 19 am" src="https://cloud.githubusercontent.com/assets/988750/25365300/14d4a6e4-29ab-11e7-949c-16650c64ec28.png">

**Comment by sentience** [comment]
In your Sublime User Preferences file, add:

```json
    "show_errors_inline": false,
```
