### ISSUE TITLE
Elm and SublimeREPL

### ISSUE THREAD

**Issue by Bernardoow** [elm-community/Elm.tmLanguage#21]
I found simple problem with menu exibition.

Fact : I haven't SublimeREPL installed.

If I check tools menu at sublime, I see blank menu [1].

I then I did a modification at menu with pr. And menu is [2].

Menu with SublimeREPL instaled is [3].

[1]  
![elm_package_bug](https://cloud.githubusercontent.com/assets/4077212/26359287/6fe55d10-3fab-11e7-81e5-a2c375b05096.png)

[2]
![elm_with_my_modification](https://cloud.githubusercontent.com/assets/4077212/26359546/24a406de-3fac-11e7-9a08-7aa49096b848.png)
[3]
![elm_with_my_modification_and_repl](https://cloud.githubusercontent.com/assets/4077212/26359581/3cf85294-3fac-11e7-8349-bc7b8db29ed4.png)

**Comment by sentience** [comment]
Fixed via #23
