### ISSUE TITLE
Can I replace tabs for spaces everywhere?

### ISSUE THREAD

**Issue by stoivo** [elm-community/Elm.tmLanguage#26]
Right now there is a mix of both.

**Comment by sentience** [comment]
See https://github.com/elm-community/Elm.tmLanguage/pull/14#issuecomment-296504631.

**Comment by stoivo** [comment]
I was mostly thinking of the python code. 

I did cause some pain. I just need to switch sublime to use tabs instead of spaces. it took mee 2 minutes to spot it. It would have taken be more time if I hadn't seen the same issue before
