### ISSUE TITLE
Update syntaxes to .sublime-syntax

### ISSUE THREAD

**Issue by stoivo** [elm-community/Elm.tmLanguage#27]
Do you want to update syntaxes to .sublime-syntax? 
This was introduced in ST3. 

Would you like this?

**Comment by sentience** [comment]
I would definitely like this! 👍

If no one else got to it first, I imagine I'd take this on when updating this package for Elm 0.19 when it is eventually released, but if you want to do it in the meantime, I would be very happy to accept such a contribution!
