### ISSUE TITLE
Double-clicking errors no longer jumps to line on OSX

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/Elm.tmLanguage#4]
In the `deadfoxygrandpa` branch (with [this 0.17 patch appiled](https://github.com/deadfoxygrandpa/Elm.tmLanguage/pull/101#issuecomment-219176599)) if I got a build error, I could double-click it to jump to the line of code in question.

This is no longer true on the `elm-community` fork; the errors display, but are not clickable.

**Comment by surfncode** [comment]
Same goes with F4 Shift-F4. They don't jump to the line of code anymore.
