### ISSUE TITLE
Syntax highlighting for 0.17 still broken with the new version, on Manjaro Linux

### ISSUE THREAD

**Issue by SandiDusic** [elm-community/Elm.tmLanguage#7]
![screenshot from 2016-07-29 20-20-01](https://cloud.githubusercontent.com/assets/1926491/17259087/32eba110-55ca-11e6-8418-3ee13b73e07d.png)

If I change the first line to `module SvgUtil where`, it works as usual. The [monkeypatched version](https://github.com/deadfoxygrandpa/Elm.tmLanguage/pull/101#issuecomment-219176599) of the pre-adoption version worked just fine.

**Comment by sentience** [comment]
I’m not able to reproduce this with the current version. Is this still a problem for you, @SandiDusic?

**Comment by SandiDusic** [comment]
Yeah, after a few reinstalls and a Sublime upgrade. What info can I provide to help?

**Comment by sentience** [comment]
@SandiDusic Are you positive you’re using an up-to-date version of the package? I just typed some of your code in to see how it behaved, and as you can see the syntax highlighting is working fine:

<img width="1116" alt="untitled_ _culture_amp" src="https://cloud.githubusercontent.com/assets/89772/21469762/9b0a3be4-cab9-11e6-9c01-cf4b34ca9ccc.png">

I suggest deleting your copy of the package and re-installing it using [Package Control](https://packagecontrol.io) to make sure you get an up-to-date (and auto-updated) version.

**Comment by SandiDusic** [comment]
> Are you positive you’re using an up-to-date version of the package?

Yes, because I'm seeing some new features.

> I suggest deleting your copy of the package and re-installing it using Package Control to make sure you get an up-to-date (and auto-updated) version.

I have.

It is a curious error. Right now I have the new version running with the monkeypatch for the old version applied, which seems to fix all the problems. Presumably I'm the only person with this behavior so I would sweat it.

**Comment by SandiDusic** [comment]
I was getting my package  from a [beta-testing repository](https://github.com/deadfoxygrandpa/Elm.tmLanguage/issues/61), which hosted the old version. Removing that repository (through the command palette) made sublime pull the new package from the official repository, fixing my problems.

**Comment by sentience** [comment]
@SandiDusic Thanks for following up! Always good to have a mysterious issue closed. 👍
